// <auto-generated />
using ContactsHillaker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsHillaker.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactsHillaker.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "1234 Sesame Street. New York City, New York, USA",
                            Name = "Alice",
                            Notes = "These are some notes on this person.",
                            Phone = "5152316759"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "1234 Sesame Street. New York City, New York, USA",
                            Name = "Bob",
                            Notes = "These are some notes on this person.",
                            Phone = "5152316759"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "1234 Sesame Street. New York City, New York, USA",
                            Name = "Candace",
                            Notes = "These are some notes on this person.",
                            Phone = "5152316759"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
